jobs:
- job: Windows
  pool:
    vmImage: VS2017-Win2016
  steps:

  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'


  - task: CmdLine@2
    inputs:
      script: 'node --max-old-space-size=12048'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Visual Studio Professional(16195a49-804b-4707-bb52-686a311b9b98)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'NODE_OPTIONS=--max_old_space_size=16384'

  - script: |
      yarn install
      yarn run watch
    displayName: 'yarn install and run watch'

  - task: Gulp@1
    inputs:
     gulpFile: 'gulpfile.js'
     targets: 'vscode-win32-x64-min'
     enableCodeCoverage: false


  - task: CopyFiles@2
    inputs:
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/build'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true


  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      ArtifactName: 'drop'
      publishLocation: 'Container'




#- job: macOS
#  pool:
#    vmImage: macOS 10.13
#  steps:
#  - template: build/azure-pipelines/darwin/continuous-build-darwin.yml