jobs:
- job: Windows
  pool:
    vmImage: VS2017-Win2016
  steps:

  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'


  - script: |
      yarn install
      yarn run watch
    displayName: 'yarn install and run watch'

  - task: Gulp@1
    inputs:
     gulpFile: 'gulpfile.js'
     targets: 'vscode-win32-x64-min'
     enableCodeCoverage: false






#- job: macOS
#  pool:
#    vmImage: macOS 10.13
#  steps:
#  - template: build/azure-pipelines/darwin/continuous-build-darwin.yml