variables:
  NODE_OPTIONS: '--max_old_space_size=16384'
  MajorVersion: 1
  MinorVersion: 0
  InitialReleaseTagNumber: 1
  IncrementReleaseTagNumber: $[counter(variables['InitialReleaseTagNumber'], 0)]

jobs:
- job: Windows
  pool:
    name: default
   # vmImage: VS2017-Win2016
  steps:

  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      yarn install
      yarn run watch
    displayName: 'yarn install and run watch'

  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: install
      workingDir: '$(Build.SourcesDirectory)'
      verbose: false

  - task: Gulp@1
    inputs:
     gulpFile: 'gulpfile.js'
     targets: 'vscode-win32-x64-min'
     enableCodeCoverage: false


# Copying the files to Staging directory. Note that for windows build 'VSCode-win32-x64' folder is created,
# hence we copying the files under 'VSCode-win32-x64' directory
  - task: CopyFiles@2
    inputs:
      SourceFolder: $(Agent.BuildDirectory)
      Contents: '**\VSCode-win32-x64\**'
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/VSCode-win32-x64/'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/VSCode-win32-x64_$(Build.BuildId).zip'
      replaceExistingArchive: true


  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/VSCode-win32-x64_$(Build.BuildId).zip'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  - task: GitHubRelease@1
    inputs:
      gitHubConnection: 'github.com_SudarshanSMD'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
     # tagSource: 'gitTag'
      tag: '$(MajorVersion).$(MinorVersion).$(IncrementReleaseTagNumber)'
      releaseNotesSource: 'inline'
      releaseNotesInline: 'Test Release'
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'

#- job: macOS
#  pool:
#    vmImage: macOS 10.13
#  steps:
#  - template: build/azure-pipelines/darwin/continuous-build-darwin.yml#