# Building vscode 

variables:
  NODE_OPTIONS: '--max_old_space_size=16384'
  MajorVersion: 1
  MinorVersion: 0
  InitialReleaseTagNumber: 1
  IncrementReleaseTagNumber: $[counter(variables['InitialReleaseTagNumber'], 0)]

jobs:
#####################################################################################################
#####                              Windows win32-x64                                            #####
#####################################################################################################
- job: Windows
  # specifying my custom pool. If you don't have one, just set the 'vmImage'
  pool:
    name: default
   #vmImage: VS2017-Win2016
  steps:

  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      yarn install
      yarn run watch
    displayName: 'yarn install and run watch'

# installing gulp. This task isn't required when Microsoft Agent is required.
# This is added for a self hosted agent
  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'install gulp -g'
    displayName: 'NPM install Gulp'

  - task: Gulp@1
    inputs:
     gulpFile: 'gulpfile.js'
     targets: 'vscode-win32-x64-min'
     enableCodeCoverage: false
    displayName: 'Gulp Task vscode-win32-x64-min'

# Archiving the. Note that for windows build 'VSCode-win32-x64' folder is created,
# hence we copying the files under 'VSCode-win32-x64' directory
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Agent.BuildDirectory)/VSCode-win32-x64/'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/VSCode-win32-x64_$(Build.BuildId).zip'
      replaceExistingArchive: true
    displayName: 'Archive the build files'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/VSCode-win32-x64_$(Build.BuildId).zip'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish archived files'
    
  - task: GitHubRelease@1
    inputs:
      gitHubConnection: 'github.com_SudarshanSMD'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
     # tagSource: 'gitTag'
      tag: '$(MajorVersion).$(MinorVersion).$(IncrementReleaseTagNumber)'
      releaseNotesSource: 'inline'
      releaseNotesInline: 'Test Release'
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'
#####################################################################################################

#####################################################################################################
#####                              Mac OS darwin                                                #####
#####################################################################################################
- job: macOS
  pool:
    vmImage: macOS 10.13
  steps:

  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      yarn install
    displayName: 'yarn install'

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'install gulp -g'
    displayName: 'NPM install Gulp'

  - task: Gulp@1
    inputs:
     gulpFile: 'gulpfile.js'
     targets: 'vscode-darwin-min'
     enableCodeCoverage: false
    displayName: 'Gulp Task vscode-darwin-min'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Agent.BuildDirectory)/VSCode-darwin/'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/VSCode-darwin_$(Build.BuildId).zip'
      replaceExistingArchive: true
    displayName: 'Archive the build files'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/VSCode-darwin_$(Build.BuildId).zip'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish archived files'
#####################################################################################################